export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  BASE_58_JOIN_CODE_PATTERN_MISMATCH: 'BASE_58_JOIN_CODE_PATTERN_MISMATCH',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ROOM_DELETE_FORBIDDEN: 'ROOM_DELETE_FORBIDDEN',
  PARTICIPANT_DELETE_FORBIDDEN: 'PARTICIPANT_DELETE_FORBIDDEN',
  MEETING_ROOM_NOT_FOUND: 'MEETING_ROOM_NOT_FOUND',
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/* 에러 코드 → i18n 번역 키 반환. 미등록 코드는 fallback 키로 매핑 */
export function getErrorKey(code: string): string {
  const isKnownCode = (Object.values(ERROR_CODES) as string[]).includes(code)
  return isKnownCode ? `common.error.${code}` : ERROR_FALLBACK_KEY
}

export const ERROR_FALLBACK_KEY = 'common.error.default'
